# Name of our workflow
name: My Test Workflow

# Define he trigger event(s)
on: [push]

# Jobs run in parallel by default, each runs in sequence
jobs:
  # Job to print something out
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, Github Actions!"
  build-and-run:
      # Job to build and test out C code
      needs: [say-hello]
      runs-on: ubuntu-latest
      steps:

        # Use github.com/actions/checkout to checkout this repo
        - name: Check out this repo
          uses: actions/checkout@v3

        - name: Install dependencies
          run: sudo apt install -y build-essential python3

        # See where we are in the VM
        - run: pwd

        # Run tests
        - name: Run tests
          run: python3 test.py
